repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/semgrep/pre-commit
    rev: v1.172.0
    hooks:
      - id: semgrep
        args: ['--config', 'auto', '--error', '--skip-unknown-extensions']
        exclude: ^fixtures/
